on:
  push:
    branches: []
  pull_request:

defaults:
  run:
    working-directory: ./server

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ruff
            command: ruff check --output-format=github .
            deps: --only lint-ruff
          - name: mypy
            command: mypy
            deps: --with lint-typing
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install ${{ matrix.deps }}
      - run: poetry run ${{ matrix.command }}

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.12"
  #     - uses: snok/install-poetry@v1
  #     - run: poetry run python -m pip install --upgrade pip setuptools
  #     - name: Install dependencies
  #       run: poetry install
  #     - run: poetry run pytest
